import SwiftUI
import PrepDataTypes
import SwiftHaptics
import SwiftUISugar
import PrepViews
import Combine
import FoodLabel

extension MealItemForm {
    public struct QuantityForm: View {
        
        @EnvironmentObject var viewModel: MealItemViewModel

        @Namespace var namespace
        @Environment(\.colorScheme) var colorScheme
        @Environment(\.dismiss) var dismiss
        @Binding var isPresented: Bool
        
        @FocusState var isFocused: Bool
        @State var animatedIsFocused: Bool = false
        @State var showingUnitPicker = false
        
        @State var showingEquivalentQuantitiesInGrid = false
        @State var equivalentQuantities: [FoodQuantity] = []
        
        public init(isPresented: Binding<Bool>) {
            _isPresented = isPresented
        }
    }
}

public extension MealItemForm.QuantityForm {

    var body: some View {
        ZStack {
            content
            VStack {
                Spacer()
                bottomButtons
            }
            .edgesIgnoringSafeArea(.bottom)
            .transition(.move(edge: .bottom))
        }
        .scrollDismissesKeyboard(.interactively)
        .navigationTitle("Quantity")
        .sheet(isPresented: $showingUnitPicker) { unitPicker }
        .toolbar { trailingCloseButton }
        .onAppear(perform: appeared)
        .onChange(of: isFocused, perform: isFocusedChanged)
    }
    
    func isFocusedChanged(to newValue: Bool) {
        withAnimation {
            animatedIsFocused = newValue
        }
    }
    
    func appeared() {
        isFocused = true
    }
    
    var content: some View {
        FormStyledScrollView {
            textFieldSection
            equivalentSection
            mealGoalsSection
            dailyGoalsSection
            foodLabelSection
//            legendSection
//            mealIncrementSection
//            goalIncrementSection
//            nutrientsSummarySection
        }
        .safeAreaInset(edge: .bottom) {
            Spacer()
                .frame(height: 80)
        }
    }
    
    var trailingCloseButton: some ToolbarContent {
        ToolbarItem(placement: .navigationBarTrailing) {
            Button {
                Haptics.feedback(style: .soft)
                isPresented = false
            } label: {
                closeButtonLabel
            }
        }
    }
}

extension MealItemForm.QuantityForm {
    var foodLabelSection: some View {
        FormStyledSection {
            foodLabel
        }
    }

    var foodLabel: FoodLabel {
        let energyBinding = Binding<FoodLabelValue>(
            get: { .init(amount: 234, unit: .kcal)  },
            set: { _ in }
        )

        let carbBinding = Binding<Double>(
            get: { 56 },
            set: { _ in }
        )

        let fatBinding = Binding<Double>(
            get: { 38  },
            set: { _ in }
        )

        let proteinBinding = Binding<Double>(
            get: { 25 },
            set: { _ in }
        )
        
        let microsBinding = Binding<[NutrientType : FoodLabelValue]>(
            get: {
                [
                    .saturatedFat : .init(amount: 22, unit: .g),
                    .sugars : .init(amount: 28, unit: .g),
                    .calcium : .init(amount: 230, unit: .mg),
                    .sodium : .init(amount: 1640, unit: .mg),
                    .transFat : .init(amount: 2, unit: .g),
                    .dietaryFiber : .init(amount: 6, unit: .g)
                ]
            },
            set: { _ in }
        )
        
        let amountBinding = Binding<String>(
            get: { "1 cup, chopped" },
            set: { _ in }
        )

        return FoodLabel(
            energyValue: energyBinding,
            carb: carbBinding,
            fat: fatBinding,
            protein: proteinBinding,
            nutrients: microsBinding,
            amountPerString: amountBinding
        )
    }
}

extension MealItemForm.QuantityForm {
    var mealGoalsSection: some View {
        var header: some View {
            HStack {
                Text("Meal Goals")
                Spacer()
                Button {
                    
                } label: {
                    HStack {
                        Text("🏋🏽‍♂️ Pre-Workout")
                            .textCase(.none)
                        Image(systemName: "chevron.up.chevron.down")
                    }
                    .foregroundColor(.accentColor)
                }
            }
        }
        
        var footer: some View {
            Text("These goals have been automatically generated by dividing your remaining daily goals by how many meals your have left to plan.")
        }
        
        return FormStyledSection(header: header, footer: footer) {
            exampleMeters
        }
    }
}

extension MealItemForm.QuantityForm {
    var dailyGoalsSection: some View {
        var header: some View {
            HStack {
                Text("Daily Goals")
                Spacer()
                Button {
                    
                } label: {
                    HStack {
                        Text("🫃🏽 Weight Loss")
                            .textCase(.none)
                        Image(systemName: "chevron.up.chevron.down")
                    }
                    .foregroundColor(.accentColor)
                }
            }
        }
        
        var footer: some View {
            LegendView(
                prepped: [.energy, .fat, .protein, .carb],
                increments: [.energy, .fat, .protein, .carb],
                showCompletion: false,
                showExcess: false
            )
        }
        
        return FormStyledSection(header: header, footer: footer) {
            exampleMeters
        }
    }
}

extension MealItemForm.QuantityForm {
    var legendSection: some View {
        FormStyledSection(header: Text("Legend")) {
            Text("Legend goes here")
        }
    }
}

struct LegendView: View {
    
    let prepped: [FoodMeterComponent]
    let increments: [FoodMeterComponent]
    let showCompletion: Bool
    let showExcess: Bool
    
    init(
        prepped: [FoodMeterComponent] = [],
        increments: [FoodMeterComponent] = [],
        showCompletion: Bool = false,
        showExcess: Bool = false
    ) {
        self.prepped = prepped
        self.increments = increments
        self.showCompletion = showCompletion
        self.showExcess = showExcess
    }

    var body: some View {
        VStack(alignment: .leading) {
            HStack(alignment: .center) {
                preppedGrid
//                    .padding(.top, Self.spacing)
                Text("This is what you've already added.")
            }
            HStack(alignment: .center) {
                incrementsGrid
//                    .padding(.top, Self.spacing)
                Text("This is what this food will be adding.")
            }
        }
    }
    
    static let spacing: CGFloat = 2
    static let colorSize: CGFloat = 10
    let cornerRadius: CGFloat = 2
    
    static let gridItem = GridItem(.fixed(colorSize), spacing: spacing)
    static let gridLayout = [gridItem, gridItem, gridItem]
    
    var preppedGrid: some View {
        LazyVGrid(columns: Self.gridLayout, spacing: Self.spacing) {
            ForEach(prepped, id: \.self) {
                colorBox($0.preppedColor)
            }
            if showCompletion {
                colorBox(FoodMeter.ViewModel.Colors.Complete.placeholder)
            }
            if showExcess {
                colorBox(FoodMeter.ViewModel.Colors.Excess.placeholder)
            }
        }
        .fixedSize()
    }

    var incrementsGrid: some View {
        LazyVGrid(columns: Self.gridLayout, spacing: Self.spacing) {
            ForEach(increments, id: \.self) {
                colorBox($0.eatenColor)
            }
            if showCompletion {
                colorBox(FoodMeter.ViewModel.Colors.Complete.fill)
            }
            if showExcess {
                colorBox(FoodMeter.ViewModel.Colors.Excess.fill)
            }
        }
        .fixedSize()
    }

    func colorBox(_ color: Color) -> some View {
        color
            .frame(width: Self.colorSize, height: Self.colorSize)
            .cornerRadius(cornerRadius)
    }
}

var exampleMeters: some View {
    VStack {
        Grid(alignment: .trailing) {
            GridRow {
                Text("Energy")
                    .foregroundColor(FoodMeterComponent.energy.textColor)
                    .fontWeight(.bold)
                    .font(.title3)
                FoodMeter(viewModel: .init(
                    component: .energy, goal: 400, burned: 0, food: 170, increment: 180))
                .frame(height: 26)
            }
            GridRow {
                Text("Carb")
                    .foregroundColor(FoodMeterComponent.carb.textColor)
                    .fontWeight(.bold)
                    .font(.title3)
                FoodMeter(viewModel: .init(
                    component: .carb, goal: 400, burned: 0, food: 170, increment: 20))
                .frame(height: 26)
            }
            GridRow {
                Text("Fat")
                    .foregroundColor(FoodMeterComponent.fat.textColor)
                    .fontWeight(.bold)
                    .font(.title3)
                FoodMeter(viewModel: .init(
                    component: .fat, goal: 300, burned: 0, food: 70, increment: 60))
                .frame(height: 26)
            }
            GridRow {
                Text("Protein")
                    .foregroundColor(FoodMeterComponent.protein.textColor)
                    .fontWeight(.bold)
                    .font(.title3)
                FoodMeter(viewModel: .init(
                    component: .protein, goal: 600, burned: 0, food: 170, increment: 70))
                .frame(height: 26)
            }
        }
    }
}

struct MiniMeters: View {
    let width: CGFloat = 60
    let height: CGFloat = 7
    let spacing: CGFloat = 2
    var body: some View {
        VStack(spacing: spacing) {
            FoodMeter(viewModel: .init(
                component: .energy, goal: 400, burned: 0, food: 170, increment: 180))
            .frame(height: height)
            FoodMeter(viewModel: .init(
                component: .carb, goal: 400, burned: 0, food: 170, increment: 20))
            .frame(height: height)
            FoodMeter(viewModel: .init(
                component: .fat, goal: 300, burned: 0, food: 70, increment: 60))
            .frame(height: height)
            FoodMeter(viewModel: .init(
                component: .protein, goal: 600, burned: 0, food: 170, increment: 70))
            .frame(height: height)
        }
        .frame(width: width)
    }
}

struct LegendViewPreview: View {
    var body: some View {
        NavigationView {
            FormStyledScrollView {
                FormStyledSection(header: Text("Daily Goals"), footer: footer) {
                    exampleMeters
                }
                FormStyledSection {
                    HStack {
                        Text("Here we go")
                        Spacer()
                        MiniMeters()
                        MiniMeters()
                    }
                }
            }
        }
    }
    
    var footer: some View {
        LegendView(
            prepped: [.energy, .fat, .protein, .carb],
            increments: [.energy, .fat, .protein, .carb],
            showCompletion: true,
            showExcess: true
        )
    }
}

struct LegendView_Previews: PreviewProvider {
    static var previews: some View {
        LegendViewPreview()
    }
}
